[homepage]
  onlyPostsInHomePage = false
  homePageLogo=true
  homePageTitle="SUGAM"
  homePageTagLine=""
  homePageLogoPath='sugam.jpg'
  homePageAbout="ML, GIS, Linguistics & more !!"
 
  homePageCoverPath='hello.jpg'
  homePageCoverTitle="Welcome to our blog and portfolio."
  homePageCoverTagLine="Discover insights, stories, and ideas that inspire. Join our community of readers exploring the latest trends and timeless wisdom.SUGAM"
  homePageSummaryLength=500
  homePagePostDate=false        
  dateFormat= "2 Jan 2006"
  showSocialLinksHome=true

[fonts]
  siteFont="Georgia, UnifrakturMaguntia, serif"

[social]
github="https://github.com/psugam/"

[theme]
  showDarkModeToggle=true
  showSearchIcon=true
  showGoToTop=true
  darkModeColor='#333333'
  lightModeColor="white"
  darkModeLinkColor='#CCCCCC'
  lightModeLinkColor='#00e'
  heroSectionColor='white' 
  darkHeroSectionColor="black"
  lightModeButton = "#007bff"
  lightModeButtonText = "#ffffff"
  lightModeButtonAlt = "transparent"
  lightModeButtonAltText = "#007bff"
  darkModeButton = "#0d6efd"
  darkModeButtonText = "#ffffff"
  darkModeButtonAlt = "transparent"
  darkModeButtonAltText = "#4d9aff"


[toc]
  numberingInTOC=false
  numberingInPost=false

[posts]
  readingSpeed=212
  showFrontMatter=true
  showDate=true
  showWordCount=true
  showAuthors=true
  showTags=true
  showCategories=true
  showReadingTime=true
  dateFormat="2 Jan 2006"
  showTagCloud=false
  showCategoryCloud=false
  showAuthorCloud=false
[rss]
  showRSS=false

[about]
  showSocialLinksPage=true

[sections]
  showDate=true
  showTags=false
  showCategories=true
  showAuthors=true
  showCoverImage=false
  showSummary=false
  showReadMore=false
  summaryLength=500
  dateFormat="2006-01-02"

 [slideshow]
  maxSize=20 

  [giscus]
enable=false
src="https://giscus.app/client.js"
  dataRepo=""
        dataRepoId=""
        dataCategory=""
        dataCategoryId=""
        dataMapping=""
        dataStrict=""
        dataReactionsEnabled=""
        dataEmitMetadata=""
        dataInputPosition=""
        dataTheme=""
        dataLang=""
        dataLoading=""
        crossorigin=""


